FEATURE_CLASSIFICATION_MAP = {
    "MoleculeProcessing": [
        "Initiator methionine",
        "Signal",
        "Transit peptide",
        "Propeptide",
        "Chain",
        "Peptide",
    ],
    "Regions": [
        "Topological domain",
        "Transmembrane",
        "Intramembrane",
        "Domain",
        "Repeat",
        "Calcium binding",
        "Zinc finger",
        "DNA binding",
        "Nucleotide binding",
        "Region",
        "Coiled coil",
        "Motif",
        "Compositional bias",
    ],
    "Sites": [
        "Active site",
        "Binding site",
        "Metal binding",
        "Site",
    ],
    "AminoAcidModifications": [
        "Non-standard residue",
        "Modified residue",
        "Lipidation",
        "Glycosylation",
        "Disulfide bond",
        "Cross-link",
    ],
    "NaturalVariations": [
        "Alternative sequence",
        "Natural variant",
    ],
    "ExperimentalInfo": [
        "Mutagenesis",
        "Sequence uncertainty",
        "Sequence conflict",
        "Non-adjacent residues",
        "Non-terminal residue",
    ],
    "SecondaryStructure": [
        "Helix",
        "Turn",
        "Beta strand",
    ],
}